import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTriggerPersonalizado, SidebarInset } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/categories-sidebar"; import { cookies } from "next/headers";
import { SiteHeader } from "@/components/site-header";
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"], });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"], });
export const metadata: Metadata = { title: "Create Next App", description: "Generated by create next app", };
export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"
  return (
    <html>
      <body>
        <SidebarProvider defaultOpen className="flex flex-col"> <SiteHeader />
          <div className="flex flex-1"> <AppSidebar />
            <SidebarInset> <main className="flex-1">
              <header className="border-b p-4 flex items-center gap-2">
                <SidebarTriggerPersonalizado />
                <h1>Navbar - Layout principal</h1>
              </header>
              <div className="p-4">
                {children}
              </div>
            </main>
            </SidebarInset>
          </div>
        </SidebarProvider>
      </body>
    </html>);
}